name: Build
on:
  push:
    branches:
    - main
    - develop
    - feature/actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        python-version: '3.9'
    - name: Install dependencies
      run: make install-test
    - name: Lint code
      run: make lint-all
    - name: Test code
      run: make test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
